spring:
  application:
    name: RecipeManagement
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:recipe
    username: sa
    password: null
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8081
  servlet:
    context-path: /api/recipemanagement
logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.kpn: DEBUG
    org.hibernate: ERROR
jwt:
  secret: recipe-app
  token:
    validity: 10000